name: semif_synthetic
channels:
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - pip=22.0.4=pyhd8ed1ab_0
  - pip:
    - hydra-core==1.1.2
    - omegaconf==2.1.2
    - opencv-python==4.5.5.64
    - pandas==1.4.2
    - pyyaml==6.0
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
# TODO update