# Settings

total_images: 3

background_fov_cm2: 7500 # bbot images, Assumed real-world field of view for backgrounds (in cm²)
# background_fov_cm2: 3000  # unsplash images Assumed real-world field of view for backgrounds (in cm²)
resize_factor: 0.25

cuts_n_image: # Number of cutouts per image
  min: 500
  max: 1500

reuse_cutouts: true  # Whether to allow reusing cutouts in multiple images
min_visibility: 0.0  # Minimum visibility ratio required for the new cutout
morphological:
  non_target_weed:  # Querying for non_target_weed == false
  non_target_weed_pred_conf:
    min:
    max:  # Confidence must be between 0.5 and 1.0
  # Filter settings for morphological properties under "cutout_props"
  is_primary: true
  extends_border: false
  validated: true
  
  bbox_area_cm2:  # Area range in cm2
    default:
      min: 10
      max: 1000
    common_name_ranges: # applies to specific common names, use default if not specified here but in the common_name list
      Mustards:
        min: 10
        max: 1000
    
    
    # very_small: [0, 0.1]
    # small: [0.1, 1]
    # medium: [1, 10]
    # medium_large: [10, 100]
    # large: [100, 1000]
    # very_large: [1000, 1000000]
  
  blur_effect:  # Blur effect threshold
    min: 
    max: 
  num_components: # Number of components range
    min:
    max:

category:
  # Filter settings for category attributes
  common_name:
    - oats
    - cereal rye
    - Crimson clover
    - red clover
    - winter pea
    - hairy vetch
    - Black Oats
    - Winter Wheat
    - Mustards
    
    # - Barley
    # - Barnyardgrass
    # - Broadleaf Signalgrass
    # - Cereal Rye
    # - Cocklebur
    # # - Colorchecker
    # - Common Lambsquarters
    # - Common Ragweed
    # - Common Sunflower
    # - Crimson Clover
    # - Cultivated Radish
    # - Fall Panicum
    # - Giant Foxtail
    # - Goosegrass
    # - Hairy Vetch
    # - Horseweed
    # - Italian Ryegrass
    # - Jimson Weed
    # - Johnsongrass
    # - Jungle Rice
    # - Kochia
    # - Large Crabgrass
    # - Maize
    # - Mustards
    # - Oats
    # - Palmer Amaranth
    # - Pitted Morning-Glory
    # - Prickly Sida
    # - Purple Nutsedge
    # - Ragweed Parthenium
    # - Red Clover
    # - Sicklepod
    # - Smooth Pigweed
    # - Soybean
    # - Spiny Amaranth
    # - Sprawling Signalgrass
    # - Texas Millet
    # - Triticale
    # # - Unknown
    # - Upland Cotton
    # - Velvetleaf
    # - Waterhemp
    # - Winter Pea
    # - Winter Wheat
    # - Yellow Foxtail
    
common_name_weights:
    crimson clover: 0.15  # clover
    red clover: 0.15      # clover
    winter pea: 0.15      # peas
    hairy vetch: 0.15     # vetch
    mustards: 0.15        # brassicas
    black oats: 0.075      # Grass
    oats: 0.075            # Grass
    cereal rye: 0.075      # Grass
    winter wheat: 0.075    # Grass
