# Settings

total_images: 2

cuts_n_image: # Number of cutouts per image
  min: 1
  max: 3

cut_distance: # Distance between cutouts in pixels
  min: 0
  max: 10000

morphological:
  # Filter settings for morphological properties under "cutout_props"
  area:  # Area range in pixels
    min: 10
    max: 100000
  blur_effect:  # Blur effect threshold
    min: 
    max: 
  eccentricity:  # Eccentricity range
    min: 
    max: 
  extends_border: true  # Only include cutouts that extend the border
  num_components: # Number of components range
    min: 1
    max: 10
  solidity:  # Solidity threshold
    min: 
    max: 
  green_sum:  # Green sum range
    min: 
    max: 
  is_primary: true  # Only include primary cutouts
  perimeter:  # Perimeter range
    min: 
    max: 

category:
  # Filter settings for category attributes
  family:  # Exact family
  genus:   # Exact genus
  group:   # Exact group
  duration: #["annual", "biennial"]  # Include either annual or biennial plants
  growth_habit:   # Growth habit
  species:   # Exact species
  subclass:   # Exact subclass
  common_name:  # Filter by common name (optional, leave empty for no filter)
