defaults:
  - synth: synth
  - cutouts: cutouts
  - _self_

hydra:
  run:
    dir: ${general.workdir}/data/projects/${general.project_name}
  output_subdir: ${general.workdir}/data/projects/${general.project_name}

datadir: 

general:
  task: config_cutouts # config_cutouts, synthesize
  project_name: all_big_cutouts
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  projectdir: ${general.workdir}/data/projects/${general.project_name}

repo_names:
  semif_annotation: SemiF-AnnotationPipeline
  semif_snyth: SemiF-SyntheticPipeline

blob_names:
  developed: semifield-developed-images
  synth: semifield-synth
  cutout: semifield-cutouts  

data:
  datadir: ${general.workdir}/data
  # datadir: /mnt/research-projects/s/screberg/longterm_storage
  developed: ${data.datadir}/${blob_names.developed}
  cutoutdir: /mnt/research-projects/s/screberg/longterm_images/semifield-cutouts # ???
  csvpath: ${general.projectdir}/${general.project_name}.csv
  
  
