defaults:
  - cutout_filters: default
  - paths: default
  - _self_

hydra:
  run:
    dir: ${paths.workdir}/projects/${project_name}/${sub_name}
  output_subdir: ${paths.workdir}/projects/${project_name}/${sub_name}


project_name: pm3d
sub_name: mixed

tasks:
  # - json_to_mongo # Deprecated
  # create_recipes:
  move_cutouts: 
  preprocess_cutouts:
  analysis:
    # - analyze_cutouts
    - analyze_preprocessed_cutouts
  # synthesize: 

move_cutouts:
  parallel: True
  parallel_workers: 8

# For each preprocessing step, specify the species 
# it should be applied to. Pass in your params to the species
# dictionary. If no params are required pass in None
# For exg/remove soil
#   1	Almost all greenish areas
#   2	Solid green vegetation
#   3	Strong green only	excludes
#   4	Very strong green	excludes 
#   5 Darkest, most saturated greens
preprocess_cutouts:
  color_correction:
    Hairy Vetch: dry
    Barley: dry
    Oats: dry
    Cereal Rye: dry
    Crimson clover: dry
  remove_soil: # applies exg filter
    # species: percentage of exg
    Hairy Vetch: 2
    Barley: 2
    Oats: 2
    Cereal Rye: 2
    Crimson clover: 2
  num_workers: 20

    
synthesize:
  parallel: false
  parallel_workers: 4
  semantic_masks: True
  instance_masks: False
  yolo_contour_labels: False  # TODO: Convert this to generate COCO-format labels instead of YOLO-style contours
  yolo_bbox_labels: False

sqlite3:
  dev_imgs: "semif_developed_images" # Table name
  cutouts: "semif_cutouts" # Table name
  db_name: "agir"