defaults:
  - cutout_filters: default
  - paths: default
  - _self_

hydra:
  run:
    dir: ${paths.workdir}/projects/${project_name}/${sub_name}
  output_subdir: ${paths.workdir}/projects/${project_name}/${sub_name}


project_name: pm3d
sub_name: mixed

tasks:
  # - json_to_mongo # Deprecated
  create_recipes:
  analysis: 
    - analyze_cutouts
  move_cutouts: 
  synthesize: 

move_cutouts:
  parallel: True
  parallel_workers: 8

preprocess_cutouts:
  exg:
    - Hairy Vetch  

synthesize:
  parallel: false
  parallel_workers: 4
  semantic_masks: True
  instance_masks: False
  yolo_contour_labels: False  # TODO: Convert this to generate COCO-format labels instead of YOLO-style contours
  yolo_bbox_labels: False

sqlite3:
  dev_imgs: "semif_developed_images" # Table name
  cutouts: "semif_cutouts" # Table name
  db_name: "agir"