defaults:
  - cutout_filters: default
  - paths: default
  - _self_

hydra:
  run:
    dir: ${paths.workdir}/projects/${general.project_name}/${general.sub_project_name}
  output_subdir: ${paths.workdir}/projects/${general.project_name}/${general.sub_project_name}

general:
  project_name: test
  sub_project_name: sub_test

tasks:
  - create_recipes
  - move_cutouts
  - synthesize

move_cutouts:
  parallel: True
  parallel_workers: 20

synthesize:
  resize_factor: 0.35 # Resize factor for the cutouts. Anything lower than 0.15 may give issues related to RandomScale transformation
  parallel: false
  parallel_workers: 4
  instance_masks: False
  yolo_contour_labels: False
  yolo_bbox_labels: True

aws:
  s3_bucket: psi-hackathon

mongodb:
  host: 40.76.253.124
  port: 27017
  db: hackathon_db
  collection: cutouts
