defaults:
  - cutout_filters: default
  - paths: default
  - _self_

hydra:
  run:
    dir: ${paths.workdir}/data/projects/${general.project_name}
  output_subdir: ${paths.workdir}/data/projects/${general.project_name}

general:
  project_name: test_cutouts

tasks:
  # - transfer_data
  # - synthesize
  - filter_cutouts

synthesize:
  parallel: False
  parallel_workers: 5