
workdir: ${hydra:runtime.cwd}  # where the code is executed
projectdir: ${paths.workdir}/data/projects/${general.project_name} # TODO: change this so that projects is it's own directory separate from data
datadir: ${paths.workdir}/data
cutoutdir: ${paths.datadir}/cutouts
backgrounddir: ${paths.datadir}/soil_images
recipesdir: ${paths.datadir}/recipe_metadata
resultsdir: ${paths.datadir}/results
species_info: /home/psa_images/SemiF-AnnotationPipeline/data/semifield-utils/species_information/species_info.json

longterm_storage: /mnt/research-projects/s/screberg/GROW_DATA/semifield-cutouts